disabled_rules:
- line_length
- force_cast
- void_return
- multiple_closures_with_trailing_closure
- unused_closure_parameter
- private_over_fileprivate

excluded:
- Carthage
- Pods
- Example

type_name:
    min_length: 1
    max_length:
        warning: 40
        error: 50
    excluded: iPhone
    allowed_symbols: ["_"]

identifier_name:
    min_length:
        warning: 1
    max_length:
        warning: 40
        error: 50
    excluded:
        - id
        - URL
        - GlobalAPIKey
